---
title: "Benthic Stressor Analysis Report"
output: html_document
params:
  table_userinput: 'NULL'
  table_compositestats: 'NULL'
  table_Togethersummary: 'NULL'
  plot_pHVA: "NULL"
  plot_pHB: "NULL"
  plot_pHE: "NULL"
  plot_pHO: "NULL"
  plot_DOVA: "NULL"
  plot_DOB: "NULL"
  plot_DOE: "NULL"
  plot_DOO: "NULL"
  plot_TNVA: "NULL"
  plot_TNB: "NULL"
  plot_TNE: "NULL"
  plot_TNO: "NULL"
  plot_TPVA: "NULL"
  plot_TPB: "NULL"
  plot_TPE: "NULL"
  plot_TPO: "NULL"
  plot_TotalHabitatVA: "NULL"
  plot_TotalHabitatB: "NULL"
  plot_TotalHabitatE: "NULL"
  plot_TotalHabitatO: "NULL"
  plot_LRBSVA: "NULL"
  plot_LRBSB: "NULL"
  plot_LRBSE: "NULL"
  plot_LRBSO: "NULL"
  plot_MetalsCCUVA: "NULL"
  plot_MetalsCCUB: "NULL"
  plot_MetalsCCUE: "NULL"
  plot_MetalsCCUO: "NULL"
  plot_SpCondVA: "NULL"
  plot_SpCondB: "NULL"
  plot_SpCondE: "NULL"
  plot_SpCondO: "NULL"
  plot_TDSVA: "NULL"
  plot_TDSB: "NULL"
  plot_TDSE: "NULL"
  plot_TDSO: "NULL"
  plot_DSulfateVA: "NULL"
  plot_DSulfateB: "NULL"
  plot_DSulfateE: "NULL"
  plot_DSulfateO: "NULL"
  plot_DChlorideVA: "NULL"
  plot_DChlorideB: "NULL"
  plot_DChlorideE: "NULL"
  plot_DChlorideO: "NULL"
  plot_DPotassiumVA: "NULL"
  plot_DPotassiumB: "NULL"
  plot_DPotassiumE: "NULL"
  plot_DPotassiumO: "NULL"
  plot_DSodiumVA: "NULL"
  plot_DSodiumB: "NULL"
  plot_DSodiumE: "NULL"
  plot_DSodiumO: "NULL"
---
### User Input Data
```{r,echo=F}
DT::datatable(params[['table_userinput']],rownames = F)
```

### Composite Statistics
```{r,echo=F}
goodtobad <- c("gray","cornflowerblue","limegreen","yellow","red")
badtogood <- c("gray","red","yellow", "limegreen","cornflowerblue")

DT::datatable(params[['table_compositestats']],rownames = F)%>%
  formatStyle(names(params[[2]])[2], backgroundColor=styleInterval(c(0,6,9),c("gray","yellow",
                                                                              "limegreen","yellow")))%>%
  formatStyle(names(params[[2]])[3], backgroundColor = styleInterval(c(0,7,8,10),badtogood)) %>%
      formatStyle(names(params[[2]])[4],backgroundColor = styleInterval(c(0,0.5,1,2),goodtobad))%>%
      formatStyle(names(params[[2]])[5], backgroundColor = styleInterval(c(0,0.02,0.05,0.1),goodtobad))%>%
      formatStyle(names(params[[2]])[6], backgroundColor = styleInterval(c(0,100,130,150),badtogood))%>%
      formatStyle(names(params[[2]])[7],backgroundColor = styleInterval(c(-3,-1.5,-1,-0.5,0.5),
                                                         c("gray","red","yellow","limegreen","cornflowerblue",
                                                           "yellow")))%>%
      formatStyle(names(params[[2]])[8], backgroundColor = styleInterval(c(0,0.75,1.5,2.0),goodtobad))%>%
      formatStyle(names(params[[2]])[9], backgroundColor = styleInterval(c(0,250,350,500),goodtobad))%>%
      formatStyle(names(params[[2]])[10], backgroundColor = styleInterval(c(0,100,250,350),goodtobad))%>%
      formatStyle(names(params[[2]])[11], backgroundColor = styleInterval(c(0,10,25,75),goodtobad))%>%
      formatStyle(names(params[[2]])[12], backgroundColor = styleInterval(c(0,10,25,50),goodtobad))%>%
      formatStyle(names(params[[2]])[13], backgroundColor = styleInterval(c(0,1,2,10),goodtobad))%>%
      formatStyle(names(params[[2]])[14], backgroundColor = styleInterval(c(0,7,10,20),goodtobad))
```

### Individual Parameter Statistics
```{r,echo=F}
DT::datatable(params[['table_Togethersummary']],rownames = F,options=list(dom = 't',pageLength=nrow(params[['table_Togethersummary']])))
```

### Statewide CDF Plots
```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_pHVA']],params[['plot_pHB']],params[['plot_pHE']],params[['plot_pHO']],
                        ncol=2)
```

```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_pHVA']],params[['plot_pHB']],params[['plot_pHE']],params[['plot_pHO']],
                        ncol=2)
```

```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_DOVA']],params[['plot_DOB']],params[['plot_DOE']],params[['plot_DOO']],
                        ncol=2)
```

```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_TNVA']],params[['plot_TNB']],params[['plot_TNE']],params[['plot_TNO']],
                        ncol=2)
```

```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_TPVA']],params[['plot_TPB']],params[['plot_TPE']],params[['plot_TPO']],
                        ncol=2)
```

```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_TotalHabitatVA']],params[['plot_TotalHabitatB']],params[['plot_TotalHabitatE']],params[['plot_TotalHabitatO']],ncol=2)
```

```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_LRBSVA']],params[['plot_LRBSB']],params[['plot_LRBSE']],params[['plot_LRBSO']],ncol=2)
```

```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_MetalsCCUVA']],params[['plot_MetalsCCUB']],params[['plot_MetalsCCUE']],params[['plot_MetalsCCUO']],ncol=2)
```


```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_SpCondVA']],params[['plot_SpCondB']],params[['plot_SpCondE']],params[['plot_SpCondO']],ncol=2)
```


```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_TDSVA']],params[['plot_TDSB']],params[['plot_TDSE']],params[['plot_TDSO']],ncol=2)
```


```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_DSulfateVA']],params[['plot_DSulfateB']],params[['plot_DSulfateE']],params[['plot_DSulfateO']],ncol=2)
```


```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_DChlorideVA']],params[['plot_DChlorideB']],params[['plot_DChlorideE']],params[['plot_DChlorideO']],ncol=2)
```


```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_DPotassiumVA']],params[['plot_DPotassiumB']],params[['plot_DPotassiumE']],params[['plot_DPotassiumO']],ncol=2)
```


```{r,echo=F,fig.height=10,fig.width=15}
gridExtra::grid.arrange(params[['plot_DSodiumVA']],params[['plot_DSodiumB']],params[['plot_DSodiumE']],params[['plot_DSodiumO']],ncol=2)
```
